####
# This Dockerfile is used in order to build a distroless container that runs the Quarkus application in native (no JVM) mode
#
# Before building the container image run:
#
# ./mvnw package -Pnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-distroless -t quarkus/cryostat-reports .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/cryostat-reports
#
###
FROM quay.io/quarkus/quarkus-distroless-image:2.0@sha256:73bbcd255f2c81a8b2ce7172518b69d377cfa063fd2f5c654ff605f67e90d56f
COPY target/*-runner /application

EXPOSE 8080
USER nonroot

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
