####
# This Dockerfile is used in order to build a distroless container that runs the Quarkus application in native (no JVM) mode
#
# Before building the container image run:
#
# ./mvnw package -Pnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-distroless -t quarkus/cryostat-reports .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/cryostat-reports
#
###
FROM quay.io/quarkus/quarkus-distroless-image:2.0@sha256:3884778f6240b1a7cd4551b988e8d244dc202f33b1f39878a37f5f9d23d069a5
COPY target/*-runner /application

EXPOSE 8080
USER nonroot

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
